[build]
  command = "pnpm build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"        # O la versión que uses
  NPM_FLAGS = "--version"    # Previene conflictos de NPM con pnpm
  NEXT_PRIVATE_TARGET = "server" # Importante si usás funciones

[[plugins]]
  package = "@netlify/plugin-nextjs"